[package]
name = "shenlong_cli"
version = "0.1.0"
edition.workspace = true
description.workspace = true
homepage.workspace = true

[dependencies]
shenlong_core = { path = "../core" }
eyre = "0.6.8"
clap = { version = "4.1.4", features = ["derive"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.25.0", features = ["full"] }
log = "0.4.17"
env_logger = "0.10.0"
owo-colors = "3.5.0"
indicatif = "0.17.3"
console = { version = "0.15", default-features = false, features = ["ansi-parsing"] }
